spring:
  datasource:
    url: jdbc:h2:mem:testdb  # In-memory database for testing
    driverClassName: org.h2.Driver
    username: sa  # Default username for H2
    password: a
  jpa:
    hibernate:
      ddl-auto: update  # Automatically create the schema (can also use 'create-drop' for tests)
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true  # Enable H2 console for browser access (optional)
